# fichier de configuration au SGBD postgreSQL

POSTGRESQL_SERVER = "bd-pedago.univ-lyon1.fr"
POSTGRESQL_USER = "p2300780"  # à remplacer par votre numéro étudiant
POSTGRESQL_PASSWORD = "Nemesis&Factoid_58"  # à remplacer par le mot de passe fourni dans Tomuss (pas votre mot de passe UCBL !)
POSTGRESQL_DATABASE = "p2300780"  # à remplacer par votre numéro étudiant
POSTGRESQL_SCHEMA = "morpion"  # à remplacer par le nom du schéma contenant vos tables (public, tp1, series, ...)
